name: Orca AppSec Demo
### example integration for orca security appsec features in a github workflow

on:
  ### UNCOMMENT THIS SECTION TO AUTOBUILD ON ANY PUSH
  #push:
  #  branches:
  #    - main
  ### UNCOMMENT THIS SECTION TO BUILD ON A REGULAR SCHEDULE
  #schedule:
  #  - cron: '38 23 */14 * *'
  ### UNCOMMENT THIS SECTION TO ENABLE ON-DEMAND BUILDS
  workflow_dispatch:
    inputs:
      mode:
        description: 'On-Demand AppSec Scan'  

env:
  REGISTRY: ghcr.io
  PROJECT_KEY: appsec-demo
     
jobs:

  iac-scan:
    name: Orca IaC Scan
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4
      ### https://github.com/orcasecurity/shiftleft-iac-action  
      - name: Run Orca IaC Scan
        id: orcasecurity_iac_scan
        uses: orcasecurity/shiftleft-iac-action@v1
        with:
          api_token: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key: ${{ env.PROJECT_KEY }}
          ### just scan the Dockerfile, or specify "terraform" etc
          path: "./Dockerfile"
          #format: "sarif"
          #output: "results/"
          ### exit code 0 means this stage will pass regardless of policy violations
          exit_code: 0
      #- name: Upload SARIF file
      #  uses: github/codeql-action/upload-sarif@v3
      #  if: ${{ always() && steps.orcasecurity_iac_scan.outputs.exit_code != 1 }}
      #  with:
      #    sarif_file: results/iac.sarif
      ### alternatively, if you want to use orca-cli instead of the iac-action:
      #- name: "Install Orca cli"
      #  run: |
      #    curl -sfL 'https://raw.githubusercontent.com/orcasecurity/orca-cli/main/install.sh' | bash -s -- -b ~/.local/bin        
      #- name: "Scan Repo"
      #  run: |
      #    ~/.local/bin/orca-cli --exit-code 0 -p "${PROJECT_KEY}" --api-token "${ORCA_SECURITY_API_TOKEN}" iac scan --path $(pwd)

  secrets-scan:
    name: Orca Secrets Scan  
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4
      ### https://github.com/orcasecurity/shiftleft-secrets-action
      - name: Run Orca Secrets Scan
        id: orcasecurity_secrets_scan
        uses: orcasecurity/shiftleft-secrets-action@v1
        with:
          api_token: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key: ${{ env.PROJECT_KEY }}
          ### path . is scanning the entire repository
          path: "."
          #format: "sarif"
          #output: "results/"
          ### exit code 0 means this stage will pass regardless of policy violations
          exit_code: 0
      ### upload SARIF file for github code scanning
      #- name: Upload SARIF file
      #  uses: github/codeql-action/upload-sarif@v3
      #  if: ${{ always() && steps.orcasecurity_secrets_scan.outputs.exit_code != 1 }}
      #  with:
      #    sarif_file: results/secrets.sarif
      ### alternatively, if you want to use orca-cli instead of the secrets-action:
      #- name: "Install Orca cli"
      #  run: |
      #    curl -sfL 'https://raw.githubusercontent.com/orcasecurity/orca-cli/main/install.sh' | bash -s -- -b ~/.local/bin
      #- name: "Scan Repo"
      #  run: |
      #    ~/.local/bin/orca-cli --exit-code 0 -p "${PROJECT_KEY}" --api-token "${ORCA_SECURITY_API_TOKEN}" secrets scan --path $(pwd)

  sast-scan:
    name: Orca SAST Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:            
      - name: "Checkout Code"
        uses: actions/checkout@v4
      ### https://github.com/orcasecurity/shiftleft-sast-action
      - name: Run Orca SAST Scan
        id: orcasecurity_sast_scan
        uses: orcasecurity/shiftleft-sast-action@v1
        with:
          api_token: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key: ${{ env.PROJECT_KEY }}
          ### path . is scanning the entire repository
          path: "."
          #format: "sarif"
          #output: "results/"
          #### exit code 0 means this stage will pass regardless of policy violations
          exit_code: 0 
      #- name: Upload SARIF file
      #  uses: github/codeql-action/upload-sarif@v3
      #  if: ${{ always() && steps.orcasecurity_sast_scan.outputs.exit_code != 1 }}
      #  with:
      #    sarif_file: results/sast.sarif
      ### alternatively, if you want to use orca-cli instead of the sast-action
      #- name: "Install Orca cli"
      #  run: |
      #    curl -sfL 'https://raw.githubusercontent.com/orcasecurity/orca-cli/main/install.sh' | bash -s -- -b ~/.local/bin            
      #- name: "Scan Repo"
      #  run: |
      #    ~/.local/bin/orca-cli --exit-code 0 -p "${PROJECT_KEY}" --api-token "${ORCA_SECURITY_API_TOKEN}" sast scan --path $(pwd)

  sca-scan:
    name: Orca SCA Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write    
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4
      ### https://github.com/orcasecurity/shiftleft-fs-action
      ### note: the "fs-action" combines SCA and Secrets scanning into one action
      ### I am disabling secret scan in this job and doing secrets scanning separately
      - name: Run Orca SCA Scan
        id: orcasecurity_sca_scan
        uses: orcasecurity/shiftleft-fs-action@v1
        with:
          api_token: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key: ${{ env.PROJECT_KEY }}
          ### path . is scanning the entire repository
          path: "."
          ### disable secrets since we're using the secrets-action separately
          disable_secret: true
          #format: "sarif"
          #output: "results/"
          ### exit code 0 means this stage will pass regardless of policy violations
          exit_code: 0 
      ### upload SARIF file for github code scanning
      #- name: Upload SARIF file
      #  uses: github/codeql-action/upload-sarif@v3
      #  if: ${{ always() && steps.orcasecurity_sca_scan.outputs.exit_code != 1 }}
      #  with:
      #    sarif_file: results/sca.sarif        
      ### alternatively, if you want to use orca-cli instead of the sca-action:
      #- name: "Install Orca cli"
      #  run: |
      #    curl -sfL 'https://raw.githubusercontent.com/orcasecurity/orca-cli/main/install.sh' | bash -s -- -b ~/.local/bin
      #- name: "Scan Repo"
      #  run: |
      #    ~/.local/bin/orca-cli --exit-code 0 -p "${PROJECT_KEY}" --api-token "${ORCA_SECURITY_API_TOKEN}" sca scan --path $(pwd)

  build:
    name: Image Build
    runs-on: ubuntu-latest
    needs: [iac-scan,secrets-scan,sast-scan,sca-scan]    
    permissions:
      id-token: write
      contents: read
      packages: write
    outputs:
      image: ${{ steps.set_image.outputs.image }}
    steps:      
    - name: "Set IMAGE Environmental Variable"
      id: set_image
      run: echo "image=${REGISTRY}/${GITHUB_REPOSITORY}:${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
    - name: "Checkout Code"
      uses: actions/checkout@v4
    - name: "Log in to the Container Registry"
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}      
    - name: "Set up Docker Buildx"
      uses: docker/setup-buildx-action@v2
    - name: "Build Local Container"
      uses: docker/build-push-action@v3
      with:
        tags: ${{ steps.set_image.outputs.image }}
        push: true
        load: false      

  image-scan:
    name: Orca Container Image Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    needs: [build]
    steps:
      ### https://github.com/orcasecurity/shiftleft-container-image-action
      - name: Run Orca Container Image Scan
        uses: orcasecurity/shiftleft-container-image-action@v1
        id: orcasecurity_container_image_scan
        with:
          api_token: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key: ${{ env.PROJECT_KEY }}
          image: ${{ needs.build.outputs.image }}
          #format: "sarif"
          #output: "results/"
          ### exit code 0 means this stage will pass regardless of policy violations
          exit_code: 0 
      #- name: Upload SARIF file
      #  uses: github/codeql-action/upload-sarif@v3
      #  if: ${{ always() && steps.orcasecurity_container_image_scan.outputs.exit_code != 1 }}
      #  with:
      #    sarif_file: results/image.sarif
      ### alternatively, if you want to use orca-cli instead of the container-image-action:
      #- name: "Install Orca cli"
      #  run: |
      #    curl -sfL 'https://raw.githubusercontent.com/orcasecurity/orca-cli/main/install.sh' | bash -s -- -b ~/.local/bin
      #- name: "Scan Image"
      #  run: |
      #    ~/.local/bin/orca-cli --exit-code 0 -p "${PROJECT_KEY}" --api-token "${ORCA_SECURITY_API_TOKEN}" image scan ${IMAGE}
